### ISSUE TITLE
Most of the links are not playable

### ISSUE THREAD

**Issue by aravindnc** [ForceGT/Tata-Sky-IPTV#10]
Hi, Thanks for the script. But most of the links are not playable in Kodi, it says one or more items failed to play. 
Not sure if that is a WIP?

**Comment by ForceGT** [comment]
Kodi acts very weird, I don't even know what to do about it
If you find out something, let me know but I have decided not to get bothered and use Tivimate instead

I will be happy to merge a PR

**Comment by aravindnc** [comment]
Oh.. But when I checked in Tivimate it says 0 channels found. Is it possible to convert the playlist file to a generic format?

**Comment by ForceGT** [comment]
#9 Maybe after this merge that should be solved, please try again and let me know

**Comment by aravindnc** [comment]
Still no luck. I guess the channel format should be m3u8 for them to support. MPD playback seems to be not supported.

**Comment by ForceGT** [comment]
I don't know what exactly the issue is for you, can you try with the Android app once?

**Comment by aravindnc** [comment]
I was checking in Kodi in Windows and was unable to play. May be it works in Android I haven't checked as my purpose is to play via PC. Anyway thanks for responding. :)

**Comment by ForceGT** [comment]
Now I get it, actually for desktop, or for Chrome on desktop I haven't found any app that can play an m3u as nicely as Tivimate does for Android, so you can try playing single links by methods mentioned in README

**Comment by saifshaikh1805** [comment]
Hey Gaurav, a lot of people are facing issues on Kodi. We should consider building an app like Tivimate for web or desktop.

**Comment by ForceGT** [comment]
@saifshaikh1805 Actually Kodi, is one of the best since it's all low level stuff. However if you insist, that you should make one, you can help around [IPTVNator](https://github.com/4gray/iptvnator) with dash mpd support. You look like a JavaScript person to me so it shouldn't be difficult to host it

**Comment by ForceGT** [comment]
Also as far as my research goes, mpd is a very varied format, as in the license mechanism is different for many different live streaming portals. HLS is easy but not that secure but since it is the industry standard and well Apple backs it, no one bats an eye

**Comment by saifshaikh1805** [comment]
Kodi was great in the past but now has too many issues. I believe it's possible to build something better for web / desktop considering that TiviMate works seamlessly on Android. However, something like that would be a big project and I might not be able to give it so much time and effort all by myself 😬

**Comment by ForceGT** [comment]
Did you check the Iptvnator thing?
It won't involve bring anything up from scratch as you can see it's already there, just some ammends

**Comment by saifshaikh1805** [comment]
I checked IPTVnator. It's good but can be extended. Also, I am looking into Google's Shaka Player library.

**Comment by Mannu-1** [comment]
Hi generating link on daily basis & sending it on tv on daily basis is a tough task does there will be any process which  generate the link automatically on daily basis.

**Comment by Nageshwar128** [comment]
> Hi generating link on daily basis & sending it on tv on daily basis is a tough task does there will be any process which generate the link automatically on daily basis.

Do you still need that even after an app has been released?

**Comment by aravindnc** [comment]
The token will get expired in 24hrs I guess, so all the links has to be refreshed for further playback. Otherwise we should run a service to generate playlist everyday.

**Comment by Nageshwar128** [comment]
Sure, I can help with that. But, You'll need to have some lil git knowledge

**Comment by ForceGT** [comment]
You guys can create a cronjob, it's easy
Or if you have the app, it's just one tap

**Comment by saifshaikh1805** [comment]
Hey Gaurav, please add the link to my repo (tata-sky-m3u) in the readme. I think it might be helpful for some people. Also, I think I can extend it and create an API on nodejs that will provide a permanent URL to the user to generate playlist without logging in everyday. But it will only be useful if the user has TiviMate premium or any IPTV player that updates the playlist each time the app is opened. Let me know your thoughts on this.

**Comment by ForceGT** [comment]
This is actually going off topic from the main issue 
So I might have a Telegram group soon where you can discuss everything
Till then I'd close it out
If you have any issues, contact me @gtxtreme or T.me/gtxtreme

**Comment by ForceGT** [comment]
[Here](T.me/tskyiptv) is the Telegram discussion group you can use for chats, suggestions issues etc
